from runtime.phases import IncidentPhase

EXPECTED_INCIDENT_PHASE_LITERALS = {
    "triage_completed",
    "triage_failed_verification",
    "triage_unverified",
    "follow_up_investigation_selected",
    "follow_up_complete_no_action",
    "follow_up_unverified",
    "follow_up_failed_verification",
    "evidence_reading_completed",
    "evidence_reading_not_applicable",
    "evidence_reading_deferred",
    "evidence_reading_unverified",
    "evidence_reading_failed_verification",
    "evidence_reading_failed_artifacts",
    "hypothesis_supported",
    "hypothesis_insufficient_evidence",
    "hypothesis_deferred",
    "hypothesis_unverified",
    "hypothesis_failed_verification",
    "hypothesis_failed_artifacts",
    "recommendation_supported",
    "recommendation_conservative",
    "recommendation_deferred",
    "recommendation_unverified",
    "recommendation_failed_verification",
    "recommendation_failed_artifacts",
    "action_stub_pending_approval",
    "action_stub_not_actionable",
    "action_stub_deferred",
    "action_stub_unverified",
    "action_stub_failed_verification",
    "action_stub_failed_artifacts",
    "action_stub_approved",
    "action_stub_denied",
    "action_execution_completed",
    "action_execution_deferred",
    "action_execution_unverified",
    "action_execution_failed_verification",
    "action_execution_failed_artifacts",
    "outcome_verification_succeeded",
    "outcome_verification_unverified",
    "outcome_verification_failed_verification",
    "outcome_verification_failed_artifacts",
}


def test_incident_phase_covers_current_implemented_literal_inventory() -> None:
    assert {phase.value for phase in IncidentPhase} == EXPECTED_INCIDENT_PHASE_LITERALS
